# Generated by Django 6.1 on 2026-08-24 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0004_alter_providerprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Confirmed')), fields=('provider_name', 'preferred_date', 'preferred_time'), name='unique_confirmed_provider_slot'),
        ),
    ]
